export const colors = {
  nodeRed:                  "#e81010",
  nodeRedHighlight:         "#ffa040",
  nodeRedHighlightSpecular: "#fff0a0",
  nodeRedDark:              "#7a0000",
  nodeRedGlow:              "#ff3300",
  nodeRedRing:              "#ffb060",
  nodeBlack:                "#1f2937",
  nodeBlackHighlight:       "#4b5563",
  nodeBlackHighlightSpecular: "#b8d8f8",
  nodeBlackDark:            "#060d14",
  nodeBlackRing:            "#7ab0d0",
  nodeText:         "#ffffff",
  edge:             "#6b7f94",
  edgeHighlight:    "#c8d8e8",
  dropShadow:       "#00000070",
} as const;
